#!/usr/bin/sh
#PBS -N hafs_forecast
#PBS -j oe
#PBS -S /bin/bash
#PBS -q dev
#PBS -A HAFS-DEV
#PBS -l walltime=02:59:00
#PBS -l place=vscatter:excl,select=48:ncpus=120:mpiprocs=60:ompthreads=2
#PBS -l debug=true
cd  $PBS_O_WORKDIR
date
start=$( date +%s )

export TOTAL_TASKS=2880
export NCTSK=60
export OMP_THREADS=2
export OMP_NUM_THREADS=2
export PURE_OMP_THREADS=2
export KMP_AFFINITY=disabled
export KMP_STACKSIZE=2048m
export HDF5_USE_FILE_LOCKING=FALSE

cd ../../BENCH.SRC.EXEC/hafs_forecast.fd/modulefiles
module use `/bin/pwd`
module load ufs_wcoss2.intel
module list
cd -
cal >p1


if [ -f "RESTART" ] || [ -d "RESTART" ]; then
   rm -rf RESTART
fi
if [ -f "OUTPUT" ] || [ -d "OUTPUT" ]; then
   rm -rf OUTPUT
fi
mkdir RESTART OUTPUT





module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich
module load cray-libsci
module load cmake
module  load ufs_wcoss2.intel




module load cray-pals
module list >listout
cal >p2
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"

export OMP_STACKSIZE=1024M
export OMP_NUM_THREADS=2
export OMP_PLACES=cores
export t1=$SECONDS
module load craype-network-ucx
   module load cray-mpich-ucx

/bin/pwd
module list 
cal >p3
mpiexec -n ${TOTAL_TASKS} --cpu-bind core --depth ${OMP_NUM_THREADS}  ../../BENCH.SRC.EXEC/exec/hafs.x >o 2>e
#mpiexec -n ${TOTAL_TASKS} --cpu-bind core --depth ${OMP_NUM_THREADS} ../hafs_forecast_mom6.x  >o 2>e

date
end=$( date +%s )
runtime=$(( end-start ))
echo "Total runtime of mpiexec " $runtime 
