#!/bin/bash

#PBS -j oe
#PBS -N C1152
#PBS -A GFS-DEV
#PBS -q dev
#PBS -l place=vscatter:excl,select=NNODES:ncpus=128
#PBS -l walltime=04:30:00

set -eux
set +e
echo -n " $( date +%s )," >  job_timestamp.txt

cd $PBS_O_WORKDIR
export CASE_DIR=$PBS_O_WORKDIR/RUNDIR/job$$
#export FCSTEXEC=/lfs/h2/nco/benchmark/noscrub/gwv/ubench/ufs-weather-model/exec/ufs.coupled.x
export FCSTEXEC=../BENCH.SRC.EXEC/ufs-weather-model/exec/ufs.coupled.x
export FCSTEXEC=./ufs_model.x
export FCSTEXEC=../sorc/ufs_model.fd/tests/ufs_model.x

 
module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich
module load cray-libsci
module load cmake
module use /lfs/f2/t2o/ptmp/emc/gwv/hr3/sorc/ufs_model.fd/modulefiles
module  load ufs_wcoss2.intel

export CONFIG_SITE=/tmp/dummy



module load cray-pals
set +x
module list >listout
set -x

echo "Model started:  " `date`
export ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"

export OMP_STACKSIZE=1024M
export OMP_NUM_THREADS=4
export OMP_PLACES=cores
##export MPICH_MPIIO_HINTS="*:romio_cb_write=disable"
set +e
############ lfs setstripe `/bin/pwd`         --stripe-count=1 --stripe-index=-1 --stripe-size=1048576

export DECOMP=32x64x.0.0.0
export t1=$SECONDS
rm o.$DECOMP oo ; ln -s o.$DECOMP oo
echo running $DECOMP with  4              theads  using  13312 tasks 416 nodes    >>TIMES
 module use /u/george.vandenberghe/w/hr5/sorc8/ufs_model.fd/modulefiles
    module load wn
       ldd ../sorc8/ufs_model.fd/tests/gfs_model.x >ldo 2>lde


module load craype-network-ucx
   module load cray-mpich-ucx
i#17504 3
mpiexec   -l -n XTASKS   -ppn 32  --cpu-bind core -depth 4 /lfs/h2/emc/eib/noscrub/gwv/gw.1103/sorc/ufs_model.fd/tests/gfs_model.x   >oo 2>ee

export EC=$?
export t2=$SECONDS
let dif=$t2'-'$t1
cp ESMF* esmf.profile.summary.$DECOMP
