#!/bin/bash -l
#SBATCH -e err
#SBATCH -o out
#SBATCH --job-name="C768cpl"
#SBATCH --account=drsa-hurr1
#SBATCH --qos=normal
#SBATCH --clusters=c6
#SBATCH --partition=batch
#SBATCH --nodes=50
#SBATCH --ntasks-per-node=192
#SBATCH --time=60
date
start=$( date +%s )

export NCTSK=60
export OMP_THREADS=1
export OMP_NUM_THREADS=1
export PURE_OMP_THREADS=1
export KMP_AFFINITY=disabled
export KMP_STACKSIZE=2048m
export HDF5_USE_FILE_LOCKING=FALSE

module load intel/2025.2 


cal >p1


if [ -f "RESTART" ] || [ -d "RESTART" ]; then
   rm -rf RESTART
fi
if [ -f "OUTPUT" ] || [ -d "OUTPUT" ]; then
   rm -rf OUTPUT
fi
mkdir RESTART OUTPUT





module load envvar/1.0
module load PrgEnv-intel/8.1.0
module load craype/2.7.8
module load intel/19.1.3.304
module load cray-mpich
module load cray-libsci
module load cmake




module load cray-pals
module list >listout
cal >p2
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"

export OMP_STACKSIZE=1024M
export OMP_NUM_THREADS=1
export OMP_PLACES=cores
export t1=$SECONDS

export OMP_STACKSIZE=1024M
export NC_BLKSZ=1M
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"
export FI_VERBS_PREFER_XRC=0
export FI_CXI_RX_MATCH_MODE=hybrid
export COMEX_EAGER_THRESHOLD=65536
export FI_CXI_RDZV_THRESHOLD=65536
#module load craype-network-ucx
#   module load cray-mpich-ucx

/bin/pwd
module list 
cal >p3

srun -l --export=all  -n 9600  --cpu-bind core --cpus-per-task=1 ../BENCH.SRC.EXEC/ufs_model.fd/exec/ufs_model.x   >o 2>e

date
end=$( date +%s )
runtime=$(( end-start ))
echo "Total runtime of mpiexec " $runtime 
