#!/bin/bash

#PBS -o out
#PBS -e err
#PBS -N run_control_c384_intel
#PBS -A GFS-DEV
#PBS -q dev
#PBS -l place=vscatter,select=6:ncpus=128:mpiprocs=128:ompthreads=1:mem=500G
#PBS -l place=excl
#PBS -l walltime=00:30:00

set -eux

cd $PBS_O_WORKDIR

echo -n " $( date +%s )," >  job_timestamp.txt

set +x
module use $PWD/modulefiles
module load modules.fv3
module load cray-pals
module list
set -x

echo "Model started:  " `date`

export OMP_STACKSIZE=512M
export OMP_NUM_THREADS=1
export OMP_PLACES=cores
export ESMF_RUNTIME_COMPLIANCECHECK=OFF:depth=4
export ESMF_RUNTIME_PROFILE=ON
export ESMF_RUNTIME_PROFILE_OUTPUT="SUMMARY"

# This "if" block is part of the rt.sh self-tests in error-test.conf. It emulates the model failing to run.
if [ "${JOB_SHOULD_FAIL:-NO}" = WHEN_RUNNING ] ; then
    echo "The job should abort now, with exit status 1." 1>&2
    echo "If error checking is working, the metascheduler should mark the job as failed." 1>&2
    false
fi

mpiexec -n 448 -ppn 128 --cpu-bind core -depth 1 ./fv3.exe 

echo "Model ended:    " `date`
echo -n " $( date +%s )," >> job_timestamp.txt
